### ISSUE TITLE
Error in installation docs

### ISSUE THREAD

**Issue by cheak1974** [xavier53348/Flet-Box#1]
Hi Everybody,

just a brief issue descritpion.

The readme explains that Flet-Box can be installed with:
```
>>> source .venv/bin/activate
>>> pip install flet
>>> pip install https://github.com/xavier53348/Flet-Box.git
```
Unfortunately this will fail due to an error inside the pip install command.

It will work if you use the follwing commands instead:
```
>>> source .venv/bin/activate
>>> pip install flet
>>> pip install git+https://github.com/xavier53348/Flet-Box.git
```

...but this isn't however installing flex-box properly I guess because I was still not able to start it with `flet ./src/flet_box.py` as there was no folder `src` in my working folder. I had to download (or clone) the repo and copy the complete `src` folder to my working folder. After doing this flet-box was starting up. Please consider to update/correct your installation instructions.

HTH

regards

Chris

**Comment by xavier53348** [comment]
Hello dev I have some errors in my computer creating pip package download manually now with git clone I have to resolve that situation today I upgrade I on beta yet but I'm adding new this
