### ISSUE TITLE
Can't install/test on mac?

### ISSUE THREAD

**Issue by bradparks** [xavier53348/Flet-Box#2]
I tried to run this on mac, but it appears there are many packages that are possibly Linux based?
Note also that requirements.txt is misspelled, as requeriments.txt

My python version:
```
$ python --version
Python 3.12.3
```

When I do 
`pip install -r requirements.txt 
`

It fails with lots of packages, which I try and remove and continue, but the following are ones I tried to remove and continue
Note that Im not super familiar with python dev, though I've been able to run all the flet examples fine, installing flet/requirements etc, and have written lots of scripts in the past, and am a java dev in the day job 😄 

```
diff --git a/requeriments.txt b/requeriments.txt
-apt-xapian-index==0.49
-catfish==4.16.3
-cliapp==1.20180812.1
-cmdtest==0.32+git
-cupshelpers==1.0
-devscripts==2.21.3+deb11u1

```

Thanks for any pointers - this looks incredible, and I'm very interested :D !

**Comment by bradparks** [comment]
Note: I've installed pyenv, and have tried also with python 3.11.9, and same issue
What version are you using?

**Comment by bradparks** [comment]
I've tried with

python 3.9.2 as well

and get errors like so

```
ERROR: Could not find a version that satisfies the requirement apt-xapian-index==0.49 (from versions: none)
ERROR: No matching distribution found for apt-xapian-index==0.49
```

If I ignored trying to install requirements.txt, and just try and run it, i am warned that pyperclip wasn't installed, so I installed it, then tried to run it again, and it loads the main screen 

```
$ pip install pyperclip
$ flet src/flet_box.py
```

**Comment by xavier53348** [comment]
Thanks bro next update will put pyperclip in requeriments g4f and pyperclip sorry by issue install manually now I'm working on scrrn manager and will be all package in pypi
